equivalent C code is generated

diff --git a/Assignment3/Makefile b/Assignment3/Makefile
--- a/Assignment3/Makefile
+++ b/Assignment3/Makefile
@@ -6,34 +6,16 @@ all:
 tests:
 	@read -p "Enter testcase filename present in 'testcases' directory: " TESTFILE ;\
 	echo ;\
-	./compiler testcases/$$TESTFILE
-
-test1:
-	@echo "testcase : bin_search.txt";
-	@echo;
-	@./compiler testcases/bin_search.txt
-
-test2:
-	@echo "testcase : bubble.txt";
-	@echo;
-	@./compiler testcases/bubble.txt
-
-test3:
-	@echo "testcase : factorial_recursive.txt";
-	@echo;
-	@./compiler testcases/factorial_recursive.txt
-
-test4:
-	@echo "testcase : Sum_Recursive,src.txt";
-	@echo;
-	@./compiler testcases/Sum_Recursive,src.txt
-
-test5:
-	@echo "testcase : test1.txt";
-	@echo;
-	@./compiler testcases/test1.txt
-
-
+	test -f testcases/$$TESTFILE || echo "Testcase file not found" ; \
+	test -f outputs/output.c ||  touch outputs/output.c ; \
+	test -f testcases/$$TESTFILE && echo "./compiler testcases/$$TESTFILE outputs/output.c" ; \
+	test -f testcases/$$TESTFILE && ./compiler testcases/$$TESTFILE outputs/output.c \
+	echo ; \
+	test -f outputs/output.c && test -f testcases/$$TESTFILE && echo "gcc outputs/output.c"; \
+	test -f outputs/output.c && test -f testcases/$$TESTFILE && gcc outputs/output.c ;\
+	test -f outputs/output.c && test -f testcases/$$TESTFILE && ./a.out;\
+	echo;\
+	test -f outputs/output.c ||  echo "Output file with C code is not generated due to errors in the testcase"; 
 
 clean:
 	rm -rf compiler y.tab.c y.tab.h lex.yy.c 
